import type { PresetMolecule } from '../types';

export const PRESET_MOLECULES: PresetMolecule[] = [
  { name: '甲烷', smiles: 'C', description: '最简单的烷烃' },
  { name: '乙烷', smiles: 'CC', description: '两个碳原子的烷烃' },
  { name: '乙烯', smiles: 'C=C', description: '含有双键的烯烃' },
  { name: '乙炔', smiles: 'C#C', description: '含有三键的炔烃' },
  { name: '丙烷', smiles: 'CCC', description: '三个碳原子的烷烃' },
  { name: '环丙烷', smiles: 'C1CC1', description: '三元环烷烃' },
  { name: '丁烷', smiles: 'CCCC', description: '四个碳原子的烷烃' },
  { name: '1-丁烯', smiles: 'C=CCC', description: '含有双键的烯烃' },
  { name: '苯', smiles: 'c1ccccc1', description: '芳香族化合物' },
  { name: '甲苯', smiles: 'Cc1ccccc1', description: '带甲基的苯' },
  { name: '异丙苯', smiles: 'CC(C)c1ccccc1', description: 'C9H12，苯环连接异丙基' },
  { name: '丙苯', smiles: 'CCCc1ccccc1', description: 'C9H12，苯环连接丙基' },
  { name: '均三甲苯', smiles: 'Cc1cc(C)cc(C)c1', description: 'C9H12，1,3,5-三甲基苯' },
  { name: '乙醇', smiles: 'CCO', description: '醇类化合物' },
  { name: '甲醇', smiles: 'CO', description: '最简单的醇' },
  { name: '乙醛', smiles: 'CC=O', description: '醛类化合物' },
  { name: '甲醛', smiles: 'C=O', description: '最简单的醛' },
  { name: '乙酸', smiles: 'CC(=O)O', description: '羧酸类化合物' },
  { name: '甲酸', smiles: 'C(=O)O', description: '最简单的羧酸' },
  { name: '丙酮', smiles: 'CC(=O)C', description: '酮类化合物' },
  { name: '氨', smiles: 'N', description: '氮氢化合物' },
  { name: '水', smiles: 'O', description: '水分子' },
];
